// let a=10;
try{
    for(i=0;i<=10 ;i++){
        console.log(i);
    }
}
catch(err){  //err is the error thrown by try
    console.log("error.....a is not defined here");
    console.log(err);
} 